src/config.rs
this keeps the configuration file & data file from clogging the home directory and is a minimal change
=> respect XDG_CONFIG_HOME and XDG_DATA_HOME

README.md, src/app.rs, src/config.rs
* Support more default config locations (inspired by alacritty).
* Support loading of app data from the legacy data path. After that,
it is stored at the proper location.
* Add config paths to the README. Resolves #10.
@goolord: You might want to take a look.
=> Follow up on #5.

src/app.rs, src/ui.rs
in most messaging apps, shift+enter enters a newline character. this pr adds that behavior.
currently i'm unable to test if this behaves as intended because running gurk panics for me
=> Alt+Enter newline shortcut

.github/workflows/ci.yaml, Cargo.lock, Cargo.toml, README.md, src/app.rs
The initial version is just a generic notification every time a message is received. I'm currently testing this with gnome-shell and it is working well. As suggested in the readme, I agree that these notifications should be optional. I imagined doing that with a config in gurk.toml but haven't tried it out yet. I'll probably submit the PR once that part is working.
=> New message notifications using notify-rust

src/ui.rs
Symlinks were recreated everytime a message with an attachment was rendered. This caused reloading of files in the preview app of images.
=> Fix attachments symlink recreation.

src/app.rs, src/main.rs
`Ctrl+A/E/W/K` - Beginning/end of input, remove word backwards, remove suffix from cursor
`Alt+Left/Right/Backspace` - Jump word left/right, remove word starting at cursor
`Home/End` - Beginning/end of input
=> Keyboard shortcuts for word navigation.

src/config.rs
Explanation here: https://github.com/boxdot/gurk-rs/issues/43
=> Fix of new config file creation error by creating missing path dirs

Cargo.lock, Cargo.toml, src/app.rs, src/signal.rs
This identifier can be stored to disk unencrypted and is derived
from the group master key.
This needed as preparation for storing ChannelId as a key in `sled`. 
This allows storing the keys in `sled` unencrypted.
=> Use group identifier as group channel id.

src/app.rs, src/ui.rs
Also:
* Do not resolve the name and color of the user for each message, but do it before.
* Use a different color for the own user name, when colors conflict in direct chat.
Fixes #16
=> Fix colors in white background terminal.

Cargo.lock, Cargo.toml, src/main.rs
This also provides better support for key modifiers which was introduced in `crossterm` 0.19.
=> Upgrade deps, and tui to 0.15, crossterm to 0.19.

src/app.rs, src/ui.rs, src/util.rs
For this, we store an offset from the last render in the
StatefulList. On rendering, we start with the offset (decreased to
selected if needed). We format all messages from the offset as long
they fit and up to the selected message (if any). Then we remove
all initial messages that did not fit (this happens when there is a
selected message outside).
=> Format only visible messages.

src/app.rs, src/main.rs
This patch allows the user to navigate words using Ctrl/Alt in combination with the arrow keys (and removing words by combining them with the Del key).
Feel free to ignore this patch if it's not in line with the keyboard shortcuts scheme you want to have for Gurk. I just thought I'd contribute it upstream as well in case it's useful to others as well.
=> Allow inter-word navigation with Alt/Ctrl+←→

src/app.rs, src/main.rs
This implements changing the active channel using Ctrl+J and Ctrl+K, similar to down/up arrow currently, but more ergonomic.
=> Ctrl+J/K for channel up/down navigation

.github/workflows/ci.yaml, .github/workflows/publish.yml, Cargo.toml, xtask/src/dist.rs
Also fix the publish workflow to compile arm targets on nightly.
Nightly is required since signal-client is using the armv8 feature
in aes which is only available on nightly. We use the version of
nightly which is defined in the toolchain file of signal-client.
Another fix is not to use clang for native compilation. It fails
for arm cross compilation.
=> Add cross compilation targets to CI and fix publish workflow.

README.md
The original install instructions in the README.md (`cargo install --git https://github.com/boxdot/gurk-rs`) now result in the following error since the introduction of xtask: 
```
error: multiple packages with binaries found: gurk, xtask
```
There is a cargo issue about this here: https://github.com/rust-lang/cargo/issues/3049 and the reported solution was to specify the package name after the git repo URL. I tried this for installing gurk and it worked.
=> Add gurk package name to cargo install command

Cargo.lock
I assume the Cargo.lock wasn't updated because a `cargo build` or `cargo update` wasn't run after the version number was updated in the Cargo.toml (and before https://github.com/boxdot/gurk-rs/commit/0045ff58a1b2a947f4cf7a2db96df8b3f95f7db5 was committed).
=> Update gurk verson in Cargo.lock to match Cargo.toml

CHANGELOG.md, src/ui.rs
=> Check of subtract to avoid overflow error in ui.rs fn draw_messages 

Cargo.lock, Cargo.toml, src/config.rs, src/signal.rs
Config now only ensures that the config dir and the data dir both
exist on save. The signal db path is not touched, since it created
automatically by presage's storage.
=> Minimize side effects in config and add tests.

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, src/app.rs, src/signal.rs, src/util.rs
Any file:// paths included in an outgoing message is sent as
attachment. Since we don't have yet storing and viewing of
attachments, we just show a replacement text if the message contains
only attachments. Otherwise, we show the message with attachments
paths removed.
=> Send attachments from file:// paths.

CHANGELOG.md, Cargo.lock
Uses the fix merged in https://github.com/whisperfish/presage/pull/36.
Fixes #101
=> Update presage and libsignal-service-rs

src/app.rs, src/main.rs, src/signal.rs, src/ui.rs
This PR should both :
- Fix #115. This issue originated in a small bug causing the client to repeatedly send empty `ReceiptMessage`s.
- Isolate the handling of these receipts. They take the form of `ReceiptEvent`s that can be created anywhere in the client and they are handled in a separate structure, stored in a set (idea from @boxdot). At regular interval (default 1 per s.; this rate can safely be increased), an event, if any, is sent. 
Technical clarification : the events are sent grouped by `Uuid` and whether they are `Delivered` or `Read`, so the number of waiting events cannot exceed `2 * (number of active conversations)`.
Shortcomings : 
- This handler does not get saved in the database. This means that closing the client while some receipt events are still waiting to get sent will …
=> Fix and isolate message receipts

CHANGELOG.md, src/app.rs, src/signal.rs, src/ui.rs
Populate the `attachments` field when receiving messages, where `filename` is the actual path stored on disk. I couldn't figure out a good way to render those paths after the messages, and I'm sure you can do it in an instant 💨
=> Add support for downloading attachments

CHANGELOG.md, Cargo.lock
This was implemented in presage. We just upgrade the dependency.
=> Show qrcode in terminal instead of PNG viewer 

.github/workflows/ci.yaml, .github/workflows/publish.yml, CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, src/app.rs, src/cursor.rs, src/main.rs, src/shortcuts.rs, src/storage.rs, src/ui.rs
Cursor tracks a byte position in a text, and additionally a column
and line. It implements navigation of left/right,line up/down,
beginning/end of a line, and basic word operation. Also it supports
unicode and characters of width > 1.
Message input now supports switching between the single line and
multi-line modes via Alt+Enter. Previously, Alt+Enter inserted a new
line. Having a special mode for multi-line is more powerful, since it
allows navigation between lines with the same shortcuts as navigation
in channels and messages. And it allows pasting multi-line text.
CI is switched to use the stable aarch64 rustc compiler. Nightly was
required due to signal-client using the armv8 feature in aes which
was only available on nightly.
Fixes #129
=> Add cursor tracking and multiline input navigation

src/app.rs
Should fix #132. It is possible to receive typing notifications from groups that have not been added to `gurk`'db, resulting in a crash when trying to find the corresponding group. Now we simply ignore these orphan notifications.
=> Return upon unknown group

src/app.rs, src/config.rs, src/ui.rs
Show ○ (sent), ◉ (received), ● (delivered) unicode icons next to own
messages. This can be disabled by adding `show_receipts = false` to
the config file.
Also optimize the receipts handling code.
=> New visual style for receipts

Cargo.lock, Cargo.toml, src/app.rs, src/main.rs, src/signal.rs, src/storage.rs, src/ui.rs, src/util.rs
Now we resolve user names from the synced address book, if possible.
We fallback to the profile name, if contact is not in the address
book. And eventually to contacts phone number, if profile retrieval
failed.
The contacts are synced on start-up of the app, however max one time
per hour.
Resolves https://github.com/boxdot/gurk-rs/issues/140
=> Sync contacts

.cargo/config.toml, .github/workflows/ci.yaml, .github/workflows/publish.yml
Use latest ubuntu and macos xcode. Also move all environment vars
into .cargo/config.toml. Since RUSTFLAGS env var overrides the
rust flags set in .cargo/config.toml, we removed RUSTFLAGS="-D
warnings".
=> Fix publish CI

CHANGELOG.md, Cargo.lock, Cargo.toml
Update all dependencies alerted by dependabot, except hyper,
traitobject, and chrono. These require upgrade of presage (which is not
trivial), removal of log4rs (cf. #158), and chrono does not have a fix
yet.
=> Security update

CHANGELOG.md, src/app.rs, src/signal.rs
Sync messages for direct messages don't contain E164 phone numbers anymore (as they should).
Note: this is extracted from #161 to avoid unrelated changes.
=> Fix receiving direct messages sent from another device

README.md
Add information on how to install `gurk-rs` under Nix/NixOS.
closes #138
=> README.md: Add Nix/NixOS installation instructions

CHANGELOG.md, Cargo.lock, Cargo.toml, src/app.rs
Name resolution from profile (via signal service) was broken due to
fetching of unversioned profile in libsignal-service. We patched the
library. The patch is not yet upstreamed and used from the main branch
due to the presage issue [62].
[62]: https://github.com/whisperfish/presage/issues/62
=> Improve name resolution

.github/workflows/ci.yaml, Cargo.lock, Cargo.toml
Crate:    chrono
Version:  0.4.19
Title:    Potential segfault in `localtime_r` invocations
Date:     2020-11-10
ID:       RUSTSEC-2020-0159
URL:      https://rustsec.org/advisories/RUSTSEC-2020-0159
Solution: Upgrade to >=0.4.20
=> Increase chrono version for vulnerability fix

CHANGELOG.md, src/app.rs, src/config.rs
In gurk's `config.toml` add
```toml
notifications = false  # default value is true
```
=> Add notifications config toggling system notifications

.gitignore, Cargo.lock, Cargo.toml, benches/app.rs, src/app.rs, src/config.rs, src/cursor.rs, src/dev.rs, src/lib.rs, src/main.rs, src/signal/mod.rs, src/signal/test.rs, src/storage.rs, src/ui/draw.rs, src/util.rs
As input for the benchmark we use a list of raw incoming messages
(metadata + base64 encoded serialized protobuf). To collect those use
the configuration
```toml
[developer]
dump_raw_messages = true
```
The benchmark measures how long it takes to process all collected
messages.
Collecting messages and running the benchmark is behind a feature
flag `dev`. Run the benchmark with
```
cargo bench --features dev
```
=> Add benchmark to measure on_message time

.github/workflows/ci.yaml, .github/workflows/publish.yml
Workaround for a segmentation fault when running xtask on
musl platforms: add explicit `--target` flag with exec platform.
=> Fix xtask musl build error

Cargo.lock, Cargo.toml, src/signal/impl.rs, src/signal/mod.rs
Upgrade presage which brings supports for sender keys. It also brings
the latest changes from libsignal-service which fix profile fetching via
profile key.
Fixes #197 
Related to #200
=> Support sender key encrypted messages

Cargo.lock, Cargo.toml
This fixes cargo audit warnings
=> Remove time 0.1 dependency and upgrade tokio

CHANGELOG.md, Cargo.lock, Cargo.toml, src/app.rs, src/data.rs, src/signal/impl.rs, src/signal/test.rs, src/storage/json.rs, src/storage/snapshots/gurk__storage__json__tests__json_storage_data_model.snap, src/ui/draw.rs
The placeholder obj tag sometimes has a space behind it and sometimes
not. For now, we replace just the obj tag, which might have several
spaces after it but it definitely works.
Closes #136
=> Implement storing and rendering of mentions

CHANGELOG.md, src/app.rs
Presage has a timeout of 3 min of contact sync. We timeout now after 10
secs. Otherwise, the app does not start. Blocking was introduced in
presage via #214.
=> Fix blocking contacts sync

Cargo.lock, Cargo.toml, src/app.rs, src/data.rs, src/event.rs, src/lib.rs, src/main.rs, src/signal/impl.rs, src/signal/manager.rs, src/signal/mod.rs, src/signal/test.rs, src/storage/json.rs, src/ui/draw.rs, src/util.rs, xtask/src/changelog.rs
Messages that could not be sent are marked as such by adding a read
field below showing the error message. The status is ephemeral and is
not stored. Resending of message is not implemented.
Also upgrade presage to incl. the fix which does not reuse websocket
connection for sending. This should fix sending messages.
=> feat: add ephemeral status to sent messages on errors

Cargo.lock, Cargo.toml, benches/app.rs, sqlx-data.json, src/config.rs, src/data.rs, src/main.rs, src/storage/copy.rs, src/storage/json.rs, src/storage/migrations/001_init.sql, src/storage/mod.rs, src/storage/sql/encoding.rs, src/storage/sql/mod.rs, src/storage/sql/storage.rs, src/storage/sql/util.rs, src/ui/draw.rs
Migration to sqlite is done on the first startup if sqlite is enabled in
the config. This feature is still quite experimental and therefore the
configuration parameters are is not exposed in readme.
=> Experimental impl of Storage via sqlite

README.md, src/cursor.rs, src/input.rs, src/main.rs, src/shortcuts.rs
It is common behavior of Ctrl+U to delete line backwards, so I wanted to have support for it in gurk.
The desired behavior is as following. Given text (cursor indicated as `|`):
```
aaaaaaaaaaaa
bbbbbbbbbbbb
ccccccc|ddddd
```
Pressing `Ctrl+U` should result into:
```
aaaaaaaaaaaa
bbbbbbbbbbbb
|ddddd
```
Pressing again should result into:
```
aaaaaaaaaaaa
bbbbbbbbbbbb|ddddd
```
Then:
```
aaaaaaaaaaaa
|ddddd
```
Then:
```
aaaaaaaaaaaa|ddddd
```
Then:
```
|ddddd
```
Further presses of `Ctrl+U` would have no effect.
Let me know if it makes sense!
=> Add support for Ctrl+U to delete line backwards

src/signal/impl.rs
I totally realize this is still a temporary solution until a proper preview is in place, but I thought it could be a bit more useful if we can in the meantime at least see what attachments there were sent.
What do you think?
=> Show attachment names or types

src/app.rs, src/config.rs
the special `print!("\x07")` do the same as a `tpul bel` or `echo -e \a` and allow to jump with WM on the last urgent window.
=> feat: Add urgent bell support 🔔

CHANGELOG.md, src/main.rs, src/signal/impl.rs, src/signal/manager.rs, src/signal/test.rs, src/storage/copy.rs, src/storage/mod.rs
Gurk copies new and changed contacts and groups from presage's signal
manager on startup. Since presage syncs the contacts when linking a new
secondary device, gurk does not start empty anymore on the first run.
Currently, presage/libsignal-service does not have an implementation for
group syncing, therefore groups are not synced.
Closes #226
=> feat: sync contacts and groups from signal manager

CHANGELOG.md, Cargo.lock, Cargo.toml, src/app.rs, src/channels.rs, src/main.rs, src/ui/coords.rs, src/ui/draw.rs, src/ui/name_resolver.rs, src/util.rs
`tui` continues to exist as the fork `ratatui`.
=> chore: replace tui with ratatui

Cargo.lock, Cargo.toml
This commit upgrades presage to the latest available version. In particular, it includes the fix for the linking of secondary devices.
For reference, the fix was done in:
<https://github.com/whisperfish/presage/pull/220>
<https://github.com/whisperfish/presage/pull/221>
<https://github.com/whisperfish/libsignal-service-rs/pull/271>
Closes #250
=> fix: message linking

Cargo.lock, Cargo.toml, src/signal/attachment.rs, src/signal/impl.rs, src/signal/mod.rs
* Attachments are now stored under
`<data_dir>/gurk/files/year-month-day/`. It is easier to open a
shorter path from terminal. Also they are nicely grouped under the
`files` folder.
* If attachment has a file name, it is used when saving it, otherwise
the first 8 chars of its hex digest are used.
* All mimes are based on the content type field are supported now. In
particular, extensions are resolved for all content types.
Also upgrade presage which now verifies the digest of downloaded
attachments.
=>  feat: store attachments under a shorter path

src/app.rs, src/data.rs
When rendering we look up the contact names in signal manager. This is an IO operation and so quite expensive. We cache now the names in memory.
=> fix: cache contact names

Cargo.lock, Cargo.toml
To bring the fix from https://github.com/whisperfish/libsignal-service-rs/pull/297
Also includes:
* Workaround UUID not found errors (https://github.com/whisperfish/presage/pull/243)
This should fix #275
=> Bump presage to e51f6f6

src/signal/impl.rs
This pr makes gurk behave like the expected behavior described in #278.
These are my first lines of rust by the way :D
____
🩹 This might still just be a bandage 🩹
How old messages are shown won't be changed by this pr rn.
I don't know enough about the 🥒 yet, to know whether changing how old messages are shown is possible.
Therefore I don't know if it's smart to apply/use this patch (more inconsistency might be harder to change/'fix' afterwards.. ?).
=> fix: show self send attachments #278

Cargo.lock
* update whoami 1.4.1 -> 1.5.1
* update h2 0.3.24 -> 0.3.26
* update insta which removes unmaintained yaml-rust
=> chore: fix security audit

.github/workflows/ci.yaml, .github/workflows/publish.yml, .gitignore, Cargo.lock, Cargo.toml, src/config.rs, src/main.rs, src/signal/mod.rs, src/storage/sql/encrypt.rs, src/storage/sql/mod.rs, src/storage/sql/storage.rs
New configuration which enables encryption of the signal keystore and
the gurk messages database:
```toml 
passphrase = "secret" 
```
Previously unencrypted database is replaced by the encrypted one. Make
sure you backup your data before enabling this option.
After enabling encryption device has to be linked again.
Closes #6
=> Key store and messages database encryption

CHANGELOG.md, src/config.rs, src/ui/draw.rs
This option is disabled by default, but can be enabled by setting the
`colored_messages` config option to `true`. The coloring is the same as
the one used for the author name.
Closes #285
=> feat: support for colored messages

.sqlx/query-1b6fc3cd9b2c351443f980ab3212bfce367a7cfc86201ddf11e25f18a9c8cdb2.json, CHANGELOG.md, src/app.rs, src/handlers.rs, src/storage/forgetful.rs, src/storage/json.rs, src/storage/memcache.rs, src/storage/mod.rs, src/storage/sql/storage.rs
The unread channel counters are now updated when a read notification is recieved from another client.
Note that the counters are ephemeral and will be reset when the app is restarted.
Marking a channel as read in Gurk does not update the unread counters in other clients yet.
Related to #286
=> feat: handle read notifications from other clients

Cargo.lock, Cargo.toml, README.md, src/app.rs, src/command.rs, src/config.rs, src/lib.rs, src/main.rs, src/ui/draw.rs
Most hardcoded shortcuts were replaced with a mode-dependent configurable shortcuts, which are mapped to abstract commands handled for easier handling.
The concept of window modes was introduced to allow conditioning bindings on e.g. whether the help mode is active or whether a message is selected. Most bindings were moved to `WindowMode.Normal`, which has the lowest priority and does not get considered when the help popup or the channel modal is shown. `WindowMode.Anywhere` takes precedence over all other modes. The remaining modes are usually inserted in between if they are active (`Multiline, MessageSelected, Normal`).
Keybindings are serialised from toml at startup. The default keybinding is active by default and can be overwritten via the configuration, e.g.
```toml …
```
=> Add command, window mode, and keybinding logic

README.md, src/app.rs, src/command.rs, src/ui/draw.rs
This fixes most of the points in #315 as well an issue that caused all `select_message` commands to be parsed as `select_message previous_entry`.
Overscroll prevention, wrapping or horizontal scrolling, and mouse wheel support for the help panel are not yet implemented.
=> Command bindings followup

Cargo.lock, Cargo.toml
Not tested yet (I had `openssl` issues when doing `cargo run` on Fedora 40).
Fixes #313
=> upgrade libsignal-client 0.51.1 -> 0.56.1

Cargo.lock, Cargo.toml, src/app.rs, src/command.rs, src/dev.rs, src/handlers.rs, src/main.rs, src/signal/impl.rs, src/signal/manager.rs, src/signal/mod.rs, src/signal/test.rs, src/storage/copy.rs, src/ui/draw.rs, src/ui/name_resolver.rs
This includes the fix https://github.com/whisperfish/presage/pull/292 in particular fixing the long-standing issue #234.
Also adjust usage of presage::Store API which is now asynchronous. One possibly negative side-effect is that the UI looks up in the contact names cache in read-only fashion, and only the async part of `gurk` can populate the cache using the store.
Also fix clippy warnings.
=> fix: random state reusage

README.md, src/app.rs, src/command.rs
Generalises #327. Configuration looks like
```
[keybindings.message_selected]
ctrl-t = "react :thumbsup:"
ctrl-h = "react ❤️"
```
=> react generalise

src/signal/mod.rs
Fixes #337. This avoids unintended relinks when encountering network issues.
=> Don't relink implicitly when the manager cannot be loaded.

README.md, src/app.rs, src/command.rs
Adds a new command `open_file` that will open the first attachment on the message. It basically works the same as the existing `open_url` command but will just open the first attachment in the message rather than the first url. 
I'm mostly using it to just open images that I receive, and so it semi-addresses https://github.com/boxdot/gurk-rs/issues/90
=> feat: add command for opening file attachments

Cargo.lock, Cargo.toml
Still playing the 🐱 and 🐭 game, this fixes a linking issue that started to happen a few days ago.
=> Bump presage to fix linking (HTTP 409: Conflict)

Cargo.lock, Cargo.toml, src/dev.rs
Brings resolution patches for the following security advisories:
- GHSA-hrrc-wpfw-5hj2
- GHSA-r58q-66g9-h6g8
=> chore: upgrade presage

src/config.rs, src/main.rs, src/signal/mod.rs
This also fixes a bug where the initial config was still using the old JSON storage.
Additionally, print deprecation warnings for the old config keys to terminal and to the log.
=> feat: disable JSON storage

src/app.rs, src/signal/attachment.rs
Remove invalid character from attachment file names. This allows to open the attachment directly from terminal by clicking on it.
Also try to open url or attachment on enter when selected a message and not having any input.
=> fix: attachments opening handling

Cargo.lock, Cargo.toml, src/config.rs, src/lib.rs, src/main.rs, src/passphrase.rs, src/signal/mod.rs, src/storage/sql/encrypt.rs, src/storage/sql/storage.rs
A passphrase is now mandatory, therefore data and signal storage are always encrypted. If no passphrase is specified as a CLI argument or in the config, the user will be prompted at startup.
=> feat: make passphrase obligatory

Cargo.lock, Cargo.toml, benches/app.rs, src/app.rs, src/config.rs, src/lib.rs, src/main.rs, src/onboarding.rs, src/passphrase.rs, src/signal/impl.rs, src/signal/mod.rs
Onboarding consists of:
- displaying a welcome message
- asking for a display name
- asking for a passphrase
- asking where to store the passphrase
On macOS, additionally allow storing the passphrase in the keychain. Also, attempt to load it from the keychain if no passphrase is provided as a CLI argument or stored in the config file.
Additionally, phone number was removed from config. Also the default config does not save paths anymore, if they have default values. In particular, this makes the config portable.
Closes #370 
Closes #360
=> feat: add onboarding flow when there is no config

Cargo.lock, Cargo.toml
This commit upgrade presage including the fix for the cache of sender certificate. In particular, it fixes fetching of the sender certificate on every send message call.
Also includes offloading decryption of large attachments to another thread.
=> fix: cache sender certificate

src/receipt.rs
Currently, we have an unreproducible bug where contacts of a gurk user get a message that a message could not be received from the user, without user actually sending a message to the contact. The only silent message we ever send is a receipt. To isolate the bug we disabled the receipts handling.
=> fix: disable receipts

.github/workflows/publish.yml
I noticed publish workflow runs on my own fork would hang for musl, and when troubleshooting, I found that the GitHub runner is a version of Ubuntu that's no longer supported. Updating to `ubuntu-latest` (like everything else) seems to fix the issue.
=> fix(publish): use latest ubuntu for musl
