src/app.rs, src/ui.rs, src/util.rs
When channels list is empty, up/down and default selection used
invalid index 0.
Fix for #4
=> Fix: invalid handling of empty channels list.

README.md
=> Fix cli linking to phone instruction link.

src/ui.rs
=> Support for older compiler than 1.44.

Cargo.lock, Cargo.toml, src/main.rs, src/signal.rs, src/ui.rs
=> Upgrade deps

src/signal.rs, src/ui.rs
This also removes bad performing code which hits filesystem on rendering of every message.
=> Remove dead attachments code.

Cargo.lock, Cargo.toml, src/app.rs, src/main.rs, src/signal.rs, src/ui.rs, src/util.rs
This also removes dead attachment code (we will need to bring it back). And we use now exclusively Rust native implementation of Signal protocol.
=> Fix automatic reconnect

src/app.rs
Explanation here: https://github.com/boxdot/gurk-rs/issues/43
=> Fix init of data file by adding creation of default when none exists

src/app.rs
=> Fix stutters.

src/app.rs, src/ui.rs
=> Handle reactions and show them as suffix of messages.

src/app.rs
This is a follow-up on #53.
* Fix missing handling of reactions from other users.
* Add notifications for reactions from other users.
Many thanks to @cleeyv for reporting the bug.
=> Handle reactions and show them as suffix of messages. (cont.)

Cargo.lock, Cargo.toml
Resolves #61 
Verified with:
```shell
cargo install --git https://github.com/gferon/gurk-rs --branch fix-build
```
=> Fix the build

src/ui.rs
=> Fix of panic from unwrap of Err in display_message

src/main.rs, src/util.rs
That feature has been requested in #68 
This is my first ever "real" contribution so please tell me if I did anything wrong!
=> Added option to disable looping back when scrolling through messages

src/ui.rs
This provides a nicer UI I think.
I had to hardcode some color value since the default text is already gray, white
didn't provide enough contrast, and dark gray was way too dark.
The current code isn't too clean I think. This is my first time writing
Rust, so let me know how I could improve it.
=> Change quoted reply-to text to a darker gray

CHANGELOG.md, Cargo.lock, Cargo.toml, src/app.rs, src/signal.rs, src/util.rs
As commented in https://github.com/boxdot/gurk-rs/issues/76#issuecomment-881863169, this fixes #76
=> Fix formatting of phone number and update user name on start.

src/main.rs
=> Allow to specify verbosity of log file

src/app.rs, src/main.rs, src/shortcuts.rs, src/signal.rs, src/ui.rs
Used to display all keyboard shortcuts + useful tips. For now, only two example shortcuts are documented.
Requested in #71.
=> Add help panel

CHANGELOG.md, README.md, src/app.rs, src/main.rs, src/shortcuts.rs, src/ui.rs
The implementation is kinda hacky but seems to do the trick. Please feel free to test various edge cases that I may have missed!
=> Basic multiline editing support

README.md, src/shortcuts.rs
All shortcuts should now be documented both in `README.md` and in the in-app help panel. Also added a section in `README.md` to document installation methods.
Addresses #71
=> Document key bindings and packages

src/app.rs
Sometimes we get an incoming message which is empty (delivery notification?). Such messages did bumped their channel up.
Also notify about attachments now.
Fixes #127
=> Fix: Notifications bumb direct messages channel up

CHANGELOG.md, Cargo.lock, Cargo.toml, src/ui.rs
The actual fix was done in https://github.com/whisperfish/presage/pull/52
=> Fix fail on contact sync for contacts without a UUID

src/app.rs, src/ui.rs
=> Add visual aid (emoji) for stickers

src/ui.rs
Solves, partially, #163 
Preview:
=> Display date only once per day

CHANGELOG.md, Cargo.lock, Cargo.toml
=> Use maintenance fixed branch of presage with updated root CA

CHANGELOG.md, src/main.rs
=> Do not create log when logging is disabled

CHANGELOG.md, README.md, src/app.rs, src/channels.rs, src/lib.rs, src/main.rs, src/shortcuts.rs, src/ui/coords.rs, src/ui/draw.rs, src/util.rs
https://asciinema.org/a/538978
=> Select channel popup

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, src/app.rs, src/config.rs, src/main.rs, src/shortcuts.rs, src/signal/impl.rs, src/signal/mod.rs, src/ui/draw.rs
Copy shortcut `alt+y` (y stands for yank).
Also add shortcuts `alt+j/k` for selecting a message.
Closes #206
=> Copy selected message to clipboard

Cargo.lock, Cargo.toml, src/app.rs, src/data.rs, src/main.rs, src/signal/impl.rs, src/signal/manager.rs, src/signal/mod.rs, src/signal/test.rs, src/ui/draw.rs
Also move contact sync to background task and do sync every 24h instead of every hour.
=> chore: upgrade presage

src/main.rs
Hello
This adds support for the bracketed paste event, where the content needs to be inserted "as is", without any formatting. Since the content can contain multiple lines, they should also be inserted as-is.
Let me know what you think!
=> Support bracketed paste

Cargo.lock, Cargo.toml, src/app.rs, src/emoji.rs, src/lib.rs, src/signal/impl.rs, src/signal/test.rs
The former crates are outdated.
=> chore: replace emoji and gh_emoji by emojis crate

Cargo.lock, Cargo.toml, src/app.rs, src/data.rs, src/main.rs, src/receipt.rs, src/signal/impl.rs, src/signal/manager.rs, src/signal/mod.rs, src/signal/test.rs, src/util.rs
This contains a lot of fixes, but I mostly wanted to test duplex receiving and sending messages to root out an issue.
=> Bump presage to 23c157b

Cargo.lock, Cargo.toml
The implementation is done in
<https://github.com/whisperfish/presage/pull/222>
=> Reconnect websockets when those are closed

src/app.rs, src/data.rs, src/ui/draw.rs, src/ui/name_resolver.rs
Also fix rendering of empty user names, and update these when ensuring that the user is known.
=> feat: utilize name offset space better

Cargo.lock, Cargo.toml
=> fix: multiple instances unlink account

.github/workflows/ci.yaml, .github/workflows/publish.yml, Cargo.lock, Cargo.toml
Also includes
* fix of loosing sync messages
<https://github.com/whisperfish/presage/pull/241>
* fix of JSON invalid padding
<https://github.com/whisperfish/libsignal-service-rs/issues/288>
=> fix: upgrade libsignal protocol 0.32.0 -> 0.40.1

src/data.rs
=> Update usage of deprecated function

src/app.rs, src/signal/impl.rs, src/signal/manager.rs, src/signal/test.rs
Only if not available fallback to the contact list name.
=> fix: use profile name

Cargo.lock, Cargo.toml, README.md
=> Add protoc prerequisite mention to README

Cargo.lock, Cargo.toml, src/dev.rs, src/main.rs, src/signal/attachment.rs, src/signal/impl.rs
=> fix: add libsignal-service/presage linking fix

README.md
(That was obvious in hindsight, but I spent a good while scanning the documentation :D)
=> doc: document ctrl+c quits

src/app.rs
See https://github.com/boxdot/gurk-rs/issues/335#issuecomment-2533238051
=> Ignore empty names from contact store

src/ui/draw.rs
This is useful on the first run, when there are no channels yet.
Closes #173
=> feat: render a message when there are no channels/messages

Cargo.lock, Cargo.toml
In particular, this includes the contact fix whisperfish/presage#296.
=> chore: update presage

Cargo.lock, Cargo.toml, benches/app.rs, src/app.rs, src/main.rs, src/signal/impl.rs, src/signal/manager.rs, src/signal/test.rs
See <https://github.com/whisperfish/presage/pull/300>.
Also the contact sync is disabled for now:
<https://github.com/boxdot/gurk-rs/issues/349>.
=> hotfix: update presage fixing connection to Signal servers

CHANGELOG.md, Cargo.lock, Cargo.toml
=> Version 0.6.1

Cargo.lock, Cargo.toml, src/ui/draw.rs, src/ui/name_resolver.rs
=> fix: strip ansi escape codes from messages text and user names

src/ui/draw.rs
=> fix: typo in error message

Cargo.lock, Cargo.toml, src/config.rs, src/main.rs, src/signal/impl.rs, src/signal/mod.rs, src/ui/draw.rs
`sqlite` config options are deprecated. Data path is now `<data_dir>/gurk.sqlite`.
=> feat: replace presage sled store with sqlite

Cargo.lock, Cargo.toml
=> fix: passphrase with special characters

.github/workflows/ci.yaml, .github/workflows/publish.yml, src/app.rs, src/emoji.rs, src/storage/forgetful.rs, src/storage/json.rs, src/storage/memcache.rs, src/storage/mod.rs, src/storage/sql/storage.rs, src/ui/draw.rs, src/ui/name_resolver.rs
Also
- Fix rust warnings
- Use xcode 16.4
- Fail on warnings
- Cancel jobs in progress on the same branch
- Only run jobs on pull request
- Enabled rust cache for clippy jobs
=> CI: speed up and improve CI
